[package]
name = "gpg-tui"
version = "0.1.0"
authors = ["Orhun Parmaksız <orhunparmaksiz@gmail.com>"]
edition = "2018"

[dependencies]
crossterm = "0.18.2"
anyhow = "1.0.36"
pretty_assertions = "0.6.1"

[dependencies.tui]
version = "0.13.0"
default-features = false
features = ["crossterm"]

[dev-dependencies]
pretty_assertions = "0.6.1"

[profile.dev]
opt-level = 0
debug = true
panic = "abort"

[profile.test]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
debug = false
panic = "abort"
lto = true
codegen-units = 1

[profile.bench]
opt-level = 3
debug = false
