[package]
name = "gpg-tui"
version = "0.1.0"
description = "Manage your GnuPG keys with ease!"
authors = ["Orhun Parmaksız <orhunparmaksiz@gmail.com>"]
license = "MIT"
homepage = "https://github.com/orhun/gpg-tui"
repository = "https://github.com/orhun/gpg-tui"
keywords = ["gnupg", "gpg", "tui", "key", "management"]
categories = ["command-line-utilities"]
edition = "2018"

[features]
tui-tests = []
gpg-tests = []

[dependencies]
gpgme = "0.9.2"
crossterm = "0.19.0"
anyhow = "1.0.40"
chrono = "0.4.19"
unicode-width = "0.1.8"
copypasta-ext = "0.3.4"
colorsys = "0.6.3"
rust-embed = "5.9.0"

[dependencies.structopt]
version = "0.3.21"
default-features = false
features = ["suggestions", "color", "wrap_help"]

[dependencies.tui]
version = "0.15.0"
default-features = false
features = ["crossterm"]

[dependencies.image]
version = "0.23.14"
default-features = false
features = ["jpeg"]

[dev-dependencies]
pretty_assertions = "0.7.2"
dirs = "3.0.2"

[profile.dev]
opt-level = 0
debug = true
panic = "abort"

[profile.test]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
debug = false
panic = "abort"
lto = true
codegen-units = 1

[profile.bench]
opt-level = 3
debug = false
