[package]
name = "gpg-tui"
version = "0.1.0"
authors = ["Orhun Parmaksız <orhunparmaksiz@gmail.com>"]
edition = "2018"

[features]
tui-tests = []
gpg-tests = []

[dependencies]
gpgme = "0.9.2"
crossterm = "0.19.0"
anyhow = "1.0.38"
chrono = "0.4.19"
unicode-width = "0.1.8"
copypasta-ext = "0.3.4"
colorsys = "0.6.3"

[dependencies.structopt]
version = "0.3.21"
default-features = false
features = ["suggestions", "color", "wrap_help"]

[dependencies.tui]
version = "0.14.0"
default-features = false
features = ["crossterm"]

[dev-dependencies]
pretty_assertions = "0.6.1"

[profile.dev]
opt-level = 0
debug = true
panic = "abort"

[profile.test]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
debug = false
panic = "abort"
lto = true
codegen-units = 1

[profile.bench]
opt-level = 3
debug = false
